import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Col, Row } from "antd";
import AvatarField from "@/components/AvatarField";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Col className='h-screen bg-gray-900'>
          <Row align={'middle'} justify={'end'} className='w-full fixed p-5'>
            <AvatarField />
          </Row>
          <Row className='w-full h-full' justify={'center'} align={'middle'}>
            {children}
          </Row>
        </Col>
      </body>
    </html>
  );
}
